### ISSUE TITLE
Unnötiger Branch

### ISSUE THREAD

**Issue by JanKoppe** [JanKoppe/publikatr#1]
Wozu wurde der develop-Bernd Branch erstellt? Das ist so nicht kompatibel mit dem Gitflow Prinzip, was wir ja für das Projekt verwenden wollen.

**Comment by fortitudo** [comment]
Das hat mir Saskia so erklärt ;-) Also entferne ich den Branch wieder...

**Comment by JanKoppe** [comment]
Feature Branches machst du nur für spezifische Features auf, die du gerade entwickelst, und nur lokal. Sobald das Feature dann fertig ist wird es wieder in den develop-branch gemerged und gepusht ;)

**Comment by fortitudo** [comment]
Ist es denn korrekt publikatr zu forken?

**Comment by k1gva** [comment]
Da hab ich mich vertan, sorry
